### ISSUE TITLE
BitsPerSample tag missing and request for more example files

### ISSUE THREAD

**Issue by cgohlke** [fei-company/EerReaderLib#4]
Thank you for releasing the EER file format specification document!

I am adding support for EER files and compression to the [tifffile](https://github.com/cgohlke/tifffile) and [imagecodecs](https://github.com/cgohlke/imagecodecs) libraries based on that specification (not the GPLed reference implementation).

I noticed that the `BitsPerSample` tag is missing from the EER frames. That means, according to the TIFF specification, the image data in the frames is of type `uint1` (one bit unsigned integer). Clearly that is not the case since more than one event can happen in a pixel. Is this on purpose or an oversight?

Could you please share more example files, especially for the Falcon C compression (65002)? I am aware of the files mentioned at https://github.com/fei-company/EerReaderLib/issues/1#issuecomment-789765979. The following files are mentioned in the specification document:
```
examples/files/0.5e4kps_2e2kps_1s.eer
examples/files/3e4kps_12e2kps_1s.eer
examples/files/falconc.eer
```

**Comment by maxime-jacquet-tfs** [comment]
Hello cgohlke,

I wanted to clarify that an EER frame is not considered an independent image; rather, it functions as a sub-part used to reconstruct the full image. Due to this nature, the BitsPerSample Tag cannot be provided for EER frames. However, you can find this information in relation to the integrated/final image, as specified in the PDF documentation on page 3.

Regarding the example files, we are in the process to add them after validation of confidentiality right.

Thank you for your understanding. If you have any further questions, please don't hesitate to ask.

**Comment by cgohlke** [comment]
Thank you. I think I got the relation between frames and integrated image. From the TIFF point of view, it is not so much that the BitsPerSample tag is missing but that the data in the strips are not really bi-level images. There are pixels with multiple counts. Or do you mean that the superresolution image is bi-level, i.e., there is only up to one count in each subpixel position (I have not verified that)? Anyway, this is easily handled in tifffile. I am looking forward to the new example files for testing.

**Comment by cgohlke** [comment]
Never mind. I was following sections 4.3 and 4.4 to implement the decoder, but from the example decoder code in section 4.5 it is evident that there is an additional increment of the pixel position after each detection. Maybe that information could be added to section 4.3?

**Comment by maxime-jacquet-tfs** [comment]
Thank you for the feedback on the documentation, I will forward this information.
